### ISSUE TITLE
argmax?

### ISSUE THREAD

**Issue by francksa** [thearn/webcam-pulse-detector#25]
Trying to use under windows 7. INstalls OK but freezes after i lock the forehead:

ValueError: attempt to get argmax of an empty sequence....

thoughts?

**Comment by gadLinux** [comment]
Hi, not for me...
face detection lock = True
Traceback (most recent call last):
  File "get_pulse.py", line 212, in <module>
    App.main_loop()
  File "get_pulse.py", line 180, in main_loop
    self.processor.run(self.selected_cam)
  File "/mnt/optional-disk/gad/git/webcam-pulse-detector/lib/processors_noopenmdao.py", line 208, in run
    idx2 = np.argmax(pruned)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 974, in argmax
    return argmax(axis, out)
ValueError: attempt to get argmax of an empty sequence


I tried... Just in case

            idx = np.where((freqs > 20) & (freqs < 240))

**Comment by gadLinux** [comment]
Adjusting camera settings with guvcview once the program started seems to make the trick.

**Comment by enochdongyi** [comment]
in processors_noopenmdao.py line 185
```
  if L > 10:
            self.output_dim = processed.shape[0]
            # print "ready"
```

change L>10 to larger number (I change it to L>50)
The error occurred when the frequency domain do not have frequency in the selected range. With higher initial sampling range, the problem can be fixed

**Comment by SkyRatInd** [comment]
> guvcview

I'm having the same error you were having, could u describe you you fixed it with a little more detail?

**Comment by POSINASUPRIYA** [comment]
After clicking S to lock the forehead location getting this error!!!!


[ WARN:0@2.402] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
face detection lock = True
Traceback (most recent call last):
 File "C:\Users\Desktop\webcam-pulse-detector-no_openmdao\get_pulse.py", line 213, in <module>
    App.main_loop()

  File "C:\Users\Desktop\webcam-pulse-detector-no_openmdao\get_pulse.py", line 181, in main_loop
    self.processor.run(self.selected_cam)

  File "C:\Users\Desktop\webcam-pulse-detector-no_openmdao\lib\processors_noopenmdao.py", line 207, in run
    idx2 = np.argmax(pruned)

  File "<__array_function__ internals>", line 5, in argmax

  File "C:\Users\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 1186, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)

  File "C:\Users\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)

ValueError: attempt to get argmax of an empty sequence


getting this error everytime when I click s to save the forehead location....can someone give me the solution!!!

**Comment by POSINASUPRIYA** [comment]
Sometimes after clicking S to lock forehead it processes and shows the heart rate. But when I try after sometime or for about a week after clicking S the video gets struck and it just captures the video and does not the heart rate. What might be the problem, I could not understand sometimes it runs well and shows the output but some times it doesn't give the output. Can someone give me the solution for this problem and the reason for this problem occurence???

**Comment by POSINASUPRIYA** [comment]
an someone provide the overall documentation of this work as there are many words like fft, RGB color model  how and where it should be used ...that need to understand.
