### ISSUE TITLE
OpenMDAO does not support uninitialized variables ?

### ISSUE THREAD

**Issue by rcompton** [thearn/webcam-pulse-detector#29]
Can't get master branch running on Ubuntu 14.04

```
(openmdao-0.12.0)aahu@barahv2:~/Downloads/webcam-pulse-detector$ python2.7 get_pulse.py 
Traceback (most recent call last):
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 1495, in _setup
    self.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 1213, in setup_sizes
    self._system.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 453, in setup_sizes
    sub.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 927, in setup_sizes
    super(SimpleSystem, self).setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 453, in setup_sizes
    sub.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 453, in setup_sizes
    sub.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 933, in setup_sizes
    self.scope.raise_exception(msg, ValueError)
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/container.py", line 1353, in raise_exception
    raise exception_class(full_msg)
ValueError: : RGBsplitter.G was not initialized. OpenMDAO does not support uninitialized variables.
Traceback (most recent call last):
  File "get_pulse.py", line 151, in <module>
    App.main_loop()
  File "get_pulse.py", line 134, in main_loop
    self.processor.run()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/component.py", line 509, in run
    self._pre_execute()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 200, in _pre_execute
    self._setup()  # only call _setup from top level
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 1495, in _setup
    self.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/assembly.py", line 1213, in setup_sizes
    self._system.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 453, in setup_sizes
    sub.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 927, in setup_sizes
    super(SimpleSystem, self).setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 453, in setup_sizes
    sub.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 453, in setup_sizes
    sub.setup_sizes()
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/systems.py", line 933, in setup_sizes
    self.scope.raise_exception(msg, ValueError)
  File "/home/aahu/Downloads/openmdao-0.12.0/local/lib/python2.7/site-packages/openmdao.main-0.12.0-py2.7.egg/openmdao/main/container.py", line 1353, in raise_exception
    raise exception_class(full_msg)
ValueError: : RGBsplitter.G was not initialized. OpenMDAO does not support uninitialized variables.
```

**Comment by rcompton** [comment]
Switched to openmdao-10.3.2 and it works fine.
