### ISSUE TITLE
TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by YUVRAJ1912** [thearn/webcam-pulse-detector#37]
Hello sir,
I got this error when i lock the forehead region
please help me......

 
face detection lock = True
Traceback (most recent call last):
  File "C:/Users/thearn-webcam-pulse-detector-3060060/thearn-webcam-pulse-detector-3060060/get_pulse.py", line 212, in <module>
    App.main_loop()
  File "C:/Users/thearn-webcam-pulse-detector-3060060/thearn-webcam-pulse-detector-3060060/get_pulse.py", line 180, in main_loop
    self.processor.run(self.selected_cam)
  File "C:\Users\thearn-webcam-pulse-detector-3060060\thearn-webcam-pulse-detector-3060060\lib\processors_noopenmdao.py", line 238, in run
    cv2.putText(self.frame_out, text,(x - w / 2, y), cv2.FONT_HERSHEY_PLAIN, tsize, col)
TypeError: integer argument expected, got float

**Comment by YUVRAJ1912** [comment]
i changed this line with this and it works......
cv2.putText(self.frame_out, text,(**int(x - w / 2)**, y), cv2.FONT_HERSHEY_PLAIN, tsize, col)
