### ISSUE TITLE
Program crashes when locking onto face

### ISSUE THREAD

**Issue by SkyRatInd** [thearn/webcam-pulse-detector#50]
Every time I hit S I get the following debug line and the program freezes:

```
WARNING: file already exists but should not: C:\Users\WORLDM~1\AppData\Local\Temp\_MEI57802\Include\pyconfig.h
init done
opengl support available
face detection lock = True
Traceback (most recent call last):
  File "<string>", line 212, in <module>
  File "<string>", line 180, in main_loop
  File "D:\webcam-pulse-detector\build\get_pulse_win\out00-PYZ.pyz\lib.processors_noopenmdao", line 208, in run
  File "D:\webcam-pulse-detector\build\get_pulse_win\out00-PYZ.pyz\numpy.core.fromnumeric", line 738, in argmax
ValueError: attempt to get argmax of an empty sequence
```

**Comment by realPetur** [comment]
Same here. 

Windows 10, python 3.6, anaconda

**Comment by yutouwd** [comment]
I have got the same problem.

**Comment by Sagarkumarsb** [comment]
Hello guys can u tell me steps to run the code because when i am running the get_pulse.py i am getting error's and even webcam is not opening and it is throwing errors like "there is no lib in c/python/....
